language: node_js
node_js:
  - "0.10"
  - "iojs-v1.4.3"
after_script: ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js ; rm -rf ./coverage

